import type { OrderRecord } from "./aiTypes";

// Mock 数据配置（仅用于演示）
const DEMO_STORE_URL = "https://demo-store.ai-beauty.example.com";
const DEMO_NOW = Date.now();

/** 计算 N 天前的 ISO 日期字符串（用于 mock 数据） */
const daysAgoISO = (days: number): string => new Date(DEMO_NOW - days * 86_400_000).toISOString();

// 🔧 辅助函数：为 mock 产品生成 lineItemId
const mockLineItemId = (orderId: string, idx: number) => `gid://shopify/LineItem/${orderId}-${idx}`;

const seedOrders: (Omit<OrderRecord, "signals"> & { signals?: string[] })[] = [
  {
    id: "4310",
    name: "#4310",
    createdAt: daysAgoISO(2),
    totalPrice: 188,
    currency: "USD",
    aiSource: "ChatGPT",
    referrer: "https://chat.openai.com/share/insight?id=4310",
    landingPage: `${DEMO_STORE_URL}/products/starter-kit?utm_source=chatgpt&utm_medium=ai-agent`,
    utmSource: "chatgpt",
    utmMedium: "ai-agent",
    sourceName: "web",
    tags: ["AI-Source-ChatGPT"],
    customerId: "c-101",
    isNewCustomer: false,
    products: [
      {
        id: "p-kit",
        lineItemId: mockLineItemId("4310", 0),
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-vitc",
        lineItemId: mockLineItemId("4310", 1),
        title: "Radiance Vitamin C Drops",
        handle: "vitamin-c-drops",
        url: `${DEMO_STORE_URL}/products/vitamin-c-drops`,
        price: 92,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "Matched referrer chat.openai.com (AI domain list)",
  },
  {
    id: "4304",
    name: "#4304",
    createdAt: daysAgoISO(6),
    totalPrice: 96,
    currency: "USD",
    aiSource: "Perplexity",
    referrer: "https://www.perplexity.ai/search?q=best+cleanser",
    landingPage: `${DEMO_STORE_URL}/products/calm-foam-cleanser?utm_source=perplexity&utm_medium=organic`,
    utmSource: "perplexity",
    utmMedium: "organic",
    sourceName: "web",
    tags: ["AI-Source-Perplexity"],
    customerId: "c-102",
    isNewCustomer: false,
    products: [
      {
        id: "p-clean",
        title: "Calm Foam Cleanser",
        handle: "calm-foam-cleanser",
        url: `${DEMO_STORE_URL}/products/calm-foam-cleanser`,
        price: 48,
        currency: "USD",
        quantity: 2,
      },
    ],
    detection: "Matched referrer perplexity.ai",
  },
  {
    id: "4299",
    name: "#4299",
    createdAt: daysAgoISO(11),
    totalPrice: 178,
    currency: "USD",
    aiSource: null,
    referrer: "https://www.instagram.com/",
    landingPage: `${DEMO_STORE_URL}/products/hydra-barrier-cream?utm_source=instagram&utm_medium=paid-social`,
    utmSource: "instagram",
    utmMedium: "paid-social",
    sourceName: "web",
    tags: [],
    customerId: "c-103",
    isNewCustomer: false,
    products: [
      {
        id: "p-hydra",
        title: "Hydra Barrier Cream",
        handle: "hydra-barrier-cream",
        url: `${DEMO_STORE_URL}/products/hydra-barrier-cream`,
        price: 124,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "No AI markers detected",
  },
  {
    id: "4287",
    name: "#4287",
    createdAt: daysAgoISO(25),
    totalPrice: 218,
    currency: "USD",
    aiSource: "ChatGPT",
    referrer: "https://chat.openai.com/share/beauty-shortlist",
    landingPage: `${DEMO_STORE_URL}/products/ceramide-repair-serum`,
    sourceName: "web",
    customerId: "c-101",
    isNewCustomer: true,
    products: [
      {
        id: "p-serum",
        title: "Ceramide Repair Serum",
        handle: "ceramide-repair-serum",
        url: `${DEMO_STORE_URL}/products/ceramide-repair-serum`,
        price: 109,
        currency: "USD",
        quantity: 2,
      },
    ],
    detection: "Matched referrer chat.openai.com",
  },
  {
    id: "4291",
    name: "#4291",
    createdAt: daysAgoISO(14),
    totalPrice: 178,
    currency: "USD",
    aiSource: "Perplexity",
    referrer: "https://www.perplexity.ai/",
    landingPage: `${DEMO_STORE_URL}/products/hydra-barrier-cream?utm_source=perplexity&utm_medium=ai-agent`,
    utmSource: "perplexity",
    utmMedium: "ai-agent",
    sourceName: "web",
    customerId: "c-102",
    isNewCustomer: true,
    products: [
      {
        id: "p-hydra",
        title: "Hydra Barrier Cream",
        handle: "hydra-barrier-cream",
        url: `${DEMO_STORE_URL}/products/hydra-barrier-cream`,
        price: 124,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "utm_source=perplexity mapped to AI channel",
  },
  {
    id: "4290",
    name: "#4290",
    createdAt: daysAgoISO(20),
    totalPrice: 198,
    currency: "USD",
    aiSource: null,
    referrer: "https://l.instagram.com/",
    landingPage: `${DEMO_STORE_URL}/products/starter-kit?utm_source=meta&utm_medium=retargeting`,
    utmSource: "meta",
    utmMedium: "retargeting",
    sourceName: "web",
    customerId: "c-103",
    isNewCustomer: true,
    products: [
      {
        id: "p-clean",
        title: "Calm Foam Cleanser",
        handle: "calm-foam-cleanser",
        url: `${DEMO_STORE_URL}/products/calm-foam-cleanser`,
        price: 48,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-kit",
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "No AI markers detected",
  },
  {
    id: "4301",
    name: "#4301",
    createdAt: daysAgoISO(8),
    totalPrice: 124,
    currency: "USD",
    aiSource: "Gemini",
    referrer: "https://gemini.google.com/app",
    landingPage: `${DEMO_STORE_URL}/products/hydra-barrier-cream?utm_source=gemini&utm_medium=assistant`,
    utmSource: "gemini",
    utmMedium: "assistant",
    sourceName: "web",
    customerId: "c-106",
    isNewCustomer: false,
    products: [
      {
        id: "p-hydra",
        title: "Hydra Barrier Cream",
        handle: "hydra-barrier-cream",
        url: `${DEMO_STORE_URL}/products/hydra-barrier-cream`,
        price: 124,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "utm_source=gemini mapped to AI channel",
  },
  {
    id: "4276",
    name: "#4276",
    createdAt: daysAgoISO(45),
    totalPrice: 144,
    currency: "USD",
    aiSource: "Gemini",
    referrer: "https://gemini.google.com/app/discover",
    landingPage: `${DEMO_STORE_URL}/products/starter-kit`,
    sourceName: "web",
    customerId: "c-106",
    isNewCustomer: true,
    products: [
      {
        id: "p-clean",
        title: "Calm Foam Cleanser",
        handle: "calm-foam-cleanser",
        url: `${DEMO_STORE_URL}/products/calm-foam-cleanser`,
        price: 48,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-kit",
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "Referrer gemini.google.com flagged as AI",
  },
  {
    id: "4281",
    name: "#4281",
    createdAt: daysAgoISO(32),
    totalPrice: 188,
    currency: "USD",
    aiSource: "Perplexity",
    referrer: "",
    landingPage: `${DEMO_STORE_URL}/products/vitamin-c-drops?utm_source=perplexity&utm_medium=ai-agent`,
    utmSource: "perplexity",
    utmMedium: "ai-agent",
    sourceName: "web",
    customerId: "c-110",
    isNewCustomer: true,
    products: [
      {
        id: "p-vitc",
        title: "Radiance Vitamin C Drops",
        handle: "vitamin-c-drops",
        url: `${DEMO_STORE_URL}/products/vitamin-c-drops`,
        price: 92,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-kit",
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "utm_source=perplexity mapped to AI channel",
  },
  {
    id: "4289",
    name: "#4289",
    createdAt: daysAgoISO(21),
    totalPrice: 156,
    currency: "USD",
    aiSource: "Copilot",
    referrer: "https://copilot.microsoft.com/",
    landingPage: `${DEMO_STORE_URL}/products/enzyme-reset-mask?utm_source=copilot&utm_medium=ai-assistant`,
    utmSource: "copilot",
    utmMedium: "ai-assistant",
    sourceName: "web",
    customerId: "c-105",
    isNewCustomer: false,
    products: [
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 2,
      },
      {
        id: "p-clean",
        title: "Calm Foam Cleanser",
        handle: "calm-foam-cleanser",
        url: `${DEMO_STORE_URL}/products/calm-foam-cleanser`,
        price: 48,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "Matched utm_source=copilot",
  },
  {
    id: "4267",
    name: "#4267",
    createdAt: daysAgoISO(60),
    totalPrice: 150,
    currency: "USD",
    aiSource: "Copilot",
    referrer: "https://copilot.microsoft.com/chat",
    landingPage: `${DEMO_STORE_URL}/products/starter-kit`,
    sourceName: "web",
    customerId: "c-105",
    isNewCustomer: true,
    products: [
      {
        id: "p-kit",
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "Referrer copilot.microsoft.com flagged as AI",
  },
  {
    id: "4254",
    name: "#4254",
    createdAt: daysAgoISO(70),
    totalPrice: 220,
    currency: "USD",
    aiSource: "ChatGPT",
    referrer: "https://chat.openai.com/",
    landingPage: `${DEMO_STORE_URL}/products/hydra-barrier-cream?utm_source=chatgpt&utm_medium=assistant`,
    utmSource: "chatgpt",
    utmMedium: "assistant",
    sourceName: "web",
    customerId: "c-109",
    isNewCustomer: true,
    products: [
      {
        id: "p-hydra",
        title: "Hydra Barrier Cream",
        handle: "hydra-barrier-cream",
        url: `${DEMO_STORE_URL}/products/hydra-barrier-cream`,
        price: 124,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-kit",
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "utm_source=chatgpt mapped to AI channel",
  },
  {
    id: "4241",
    name: "#4241",
    createdAt: daysAgoISO(3),
    totalPrice: 146,
    currency: "USD",
    aiSource: "Other-AI",
    referrer: "https://claude.ai/chat",
    landingPage: `${DEMO_STORE_URL}/products/vitamin-c-drops?utm_medium=ai-assistant`,
    utmMedium: "ai-assistant",
    sourceName: "web",
    customerId: "c-111",
    isNewCustomer: false,
    products: [
      {
        id: "p-vitc",
        title: "Radiance Vitamin C Drops",
        handle: "vitamin-c-drops",
        url: `${DEMO_STORE_URL}/products/vitamin-c-drops`,
        price: 92,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "Referrer claude.ai matched Other-AI",
  },
  {
    id: "4229",
    name: "#4229",
    createdAt: daysAgoISO(85),
    totalPrice: 102,
    currency: "USD",
    aiSource: "Other-AI",
    referrer: "https://deepseek.com/assistant",
    landingPage: `${DEMO_STORE_URL}/products/enzyme-reset-mask?utm_source=deepseek`,
    utmSource: "deepseek",
    sourceName: "web",
    customerId: "c-111",
    isNewCustomer: true,
    products: [
      {
        id: "p-clean",
        title: "Calm Foam Cleanser",
        handle: "calm-foam-cleanser",
        url: `${DEMO_STORE_URL}/products/calm-foam-cleanser`,
        price: 48,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "utm_source=deepseek mapped to Other-AI",
  },
  {
    id: "4309",
    name: "#4309",
    createdAt: daysAgoISO(1),
    totalPrice: 96,
    currency: "USD",
    aiSource: null,
    referrer: "https://t.co/brand-email",
    landingPage: `${DEMO_STORE_URL}/products/starter-kit?utm_source=email&utm_medium=crm`,
    utmSource: "email",
    utmMedium: "crm",
    sourceName: "web",
    customerId: "c-104",
    isNewCustomer: false,
    products: [
      {
        id: "p-kit",
        title: "Starter Discovery Kit",
        handle: "starter-kit",
        url: `${DEMO_STORE_URL}/products/starter-kit`,
        price: 96,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "No AI markers detected",
  },
  {
    id: "4306",
    name: "#4306",
    createdAt: daysAgoISO(4),
    totalPrice: 102,
    currency: "USD",
    aiSource: null,
    referrer: "https://www.google.com/",
    landingPage: `${DEMO_STORE_URL}/products/enzyme-reset-mask?utm_source=google&utm_medium=organic`,
    utmSource: "google",
    utmMedium: "organic",
    sourceName: "web",
    customerId: "c-104",
    isNewCustomer: true,
    products: [
      {
        id: "p-clean",
        title: "Calm Foam Cleanser",
        handle: "calm-foam-cleanser",
        url: `${DEMO_STORE_URL}/products/calm-foam-cleanser`,
        price: 48,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-mask",
        title: "Enzyme Reset Mask",
        handle: "enzyme-reset-mask",
        url: `${DEMO_STORE_URL}/products/enzyme-reset-mask`,
        price: 54,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "No AI markers detected",
  },
  {
    id: "4269",
    name: "#4269",
    createdAt: daysAgoISO(50),
    totalPrice: 233,
    currency: "USD",
    aiSource: null,
    referrer: "https://www.reddit.com/",
    landingPage: `${DEMO_STORE_URL}/products/hydra-barrier-cream?utm_source=reddit&utm_medium=organic`,
    utmSource: "reddit",
    utmMedium: "organic",
    sourceName: "web",
    customerId: "c-108",
    isNewCustomer: true,
    products: [
      {
        id: "p-hydra",
        title: "Hydra Barrier Cream",
        handle: "hydra-barrier-cream",
        url: `${DEMO_STORE_URL}/products/hydra-barrier-cream`,
        price: 124,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-serum",
        title: "Ceramide Repair Serum",
        handle: "ceramide-repair-serum",
        url: `${DEMO_STORE_URL}/products/ceramide-repair-serum`,
        price: 109,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "No AI markers detected",
  },
  {
    id: "4295",
    name: "#4295",
    createdAt: daysAgoISO(12),
    totalPrice: 216,
    currency: "USD",
    aiSource: null,
    referrer: "https://www.bing.com/",
    landingPage: `${DEMO_STORE_URL}/products/hydra-barrier-cream?utm_source=bing&utm_medium=seo`,
    utmSource: "bing",
    utmMedium: "seo",
    sourceName: "web",
    customerId: "c-112",
    isNewCustomer: true,
    products: [
      {
        id: "p-hydra",
        title: "Hydra Barrier Cream",
        handle: "hydra-barrier-cream",
        url: `${DEMO_STORE_URL}/products/hydra-barrier-cream`,
        price: 124,
        currency: "USD",
        quantity: 1,
      },
      {
        id: "p-vitc",
        title: "Radiance Vitamin C Drops",
        handle: "vitamin-c-drops",
        url: `${DEMO_STORE_URL}/products/vitamin-c-drops`,
        price: 92,
        currency: "USD",
        quantity: 1,
      },
    ],
    detection: "No AI markers detected",
  },
];

export const mockOrders: OrderRecord[] = seedOrders.map((order) => ({
  ...order,
  signals: order.signals ?? [],
  // 🔧 自动为缺少 lineItemId 的产品生成唯一标识
  products: order.products.map((p, idx) => ({
    ...p,
    lineItemId: p.lineItemId || mockLineItemId(order.id, idx),
  })),
}));

