-- AlterTable
ALTER TABLE "BackfillJob"
ADD COLUMN     "rangeStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "rangeEnd" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "maxOrders" INTEGER,
ADD COLUMN     "maxDurationMs" INTEGER;
