// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/orders/updated": {
    params: {};
  };
  "/webhooks/orders/create": {
    params: {};
  };
  "/api/llms-txt-preview": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/api/retention": {
    params: {};
  };
  "/api/backfill": {
    params: {};
  };
  "/api/copilot": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/api/jobs": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/copilot": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/orders/updated" | "/webhooks/orders/create" | "/api/llms-txt-preview" | "/webhooks/shop/redact" | "/api/retention" | "/api/backfill" | "/api/copilot" | "/auth/login" | "/api/jobs" | "/auth/*" | "/app" | "/app/additional" | "/app/copilot";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.orders.updated.tsx": {
    id: "routes/webhooks.orders.updated";
    page: "/webhooks/orders/updated";
  };
  "routes/webhooks.orders.create.tsx": {
    id: "routes/webhooks.orders.create";
    page: "/webhooks/orders/create";
  };
  "routes/api.llms-txt-preview.tsx": {
    id: "routes/api.llms-txt-preview";
    page: "/api/llms-txt-preview";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/api.retention.tsx": {
    id: "routes/api.retention";
    page: "/api/retention";
  };
  "routes/api.backfill.tsx": {
    id: "routes/api.backfill";
    page: "/api/backfill";
  };
  "routes/api.copilot.tsx": {
    id: "routes/api.copilot";
    page: "/api/copilot";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/api.jobs.tsx": {
    id: "routes/api.jobs";
    page: "/api/jobs";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/additional" | "/app/copilot";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.copilot.tsx": {
    id: "routes/app.copilot";
    page: "/app/copilot";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.orders.updated": typeof import("./app/routes/webhooks.orders.updated.tsx");
  "routes/webhooks.orders.create": typeof import("./app/routes/webhooks.orders.create.tsx");
  "routes/api.llms-txt-preview": typeof import("./app/routes/api.llms-txt-preview.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/api.retention": typeof import("./app/routes/api.retention.tsx");
  "routes/api.backfill": typeof import("./app/routes/api.backfill.tsx");
  "routes/api.copilot": typeof import("./app/routes/api.copilot.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/api.jobs": typeof import("./app/routes/api.jobs.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.copilot": typeof import("./app/routes/app.copilot.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};